backend:
  name: github
  repo: vladkamarketing-bit/vladka-web
  branch: master
  base_url: https://vladka-web.vercel.app
  auth_endpoint: api/auth

media_folder: public/images
public_folder: /images

collections:
  - name: "pages"
    label: "Stránky"
    files:
      - name: "homepage"
        label: "Hlavní stránka"
        file: "src/content/homepage.json"
        fields:
          - { label: "Nadpis hero", name: "heroTitle", widget: "string" }
          - { label: "Popis hero", name: "heroSubtitle", widget: "text" }
